---
title: "Burneyville Mesonet Soil Conditions"
output:
  pdf_document: default
  html_document:
    df_print: paged
---


```{r header, eval=FALSE, include=FALSE}
## CodeMonkey:  Mike Proctor
## ============================================================
## 
## Generates soil temperature graphs from data downloaded by Mesonet_DLoads.RMD and processed by Mesonet_Processing.R
## 
## 
```

```{r Setup, message=FALSE, warning=FALSE, include=FALSE}
library(readr)       ##  "Import dataset" uses this
library(tidyverse)   ##  mutate, transform etc.
library(lubridate)   ##  requried for ts to work
library(magrittr)    ##  %>% - pipe
library(rprojroot)   ##  find_rstudio_root_file()
library("tidylog", warn.conflicts = FALSE)
library(tictoc)

# 2019-12-05 09:47:49 ------------------------------mdp

## Local stuff  =================
base_path   <- find_rstudio_root_file()                        ## Finds path for project
source_path <- file.path(base_path, "source_data//")           ## these 4 should
dat_path    <- file.path(base_path, "dat_output//")            ## be existing
plot_path   <- file.path(base_path, "plots//")                 ## folders in
csv_path    <- file.path(base_path, "csv_output//")            ## project
```



```{r Load and process files, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
# Configured for these variables in 01_Mesonet_DLoads.Rmd
#meso_variables <-  c("RAIN", "TAIR", "TS05", "TS10", "TR05", "TR25")


soilVals <- read_csv("dat_output/Mesonet_2012_1_1_2021_12_31.dat")


SoilsNA <- soilVals %>% filter(!is.na(Soil_Temp_Veg_4inch) & ##  Soil temps are at 15min intervals so drop NAs
                               !is.na(Soil_Temp_Veg_2inch) & 
                               !is.na(FWI_2) &
                               !is.na(FWI_10))  




```


```{r summarize1, message=FALSE, include=FALSE}


SoilDaily <- SoilsNA %>% group_by(month(TIME), day(TIME)) %>% 
  mutate("Soil_Temp_Veg_2inch_daily" = mean(Soil_Temp_Veg_2inch),
         "Soil_Temp_Veg_4inch_daily" = mean(Soil_Temp_Veg_4inch),
         "FWI_2inch_daily" = mean(FWI_2),
         "FWI_10inch_daily" = mean(FWI_10),
         "Temp_daily" = mean(Temp)
         ) %>% ungroup()

#awol <- SoilDaily %>% filter(year(TIME) == "2014") # 2014 only has 3 months of data




```



None of this is plotting properly except for air temps



##  Soil Temperatures

```{r Plot Soil Temps, echo=FALSE, message=FALSE, warning=FALSE}


  ggplot(SoilDaily, aes(x = TIME)) +
     geom_line(aes(y = Soil_Temp_Veg_2inch_daily, color = "2 inch Soil Temp")) +
     scale_color_manual(name = "Soil Temps", values = c("2 inch Soil Temp" = "blue", 
                                                        "4 inch Soil Temp" = "green"))+
     geom_line(aes(y = Soil_Temp_Veg_4inch_daily, color = "4 inch Soil Temp")) +
     theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))  +
     xlab("Month")+
     ylab("Temperature F")+
     #scale_x_discrete(limits = month.abb) +
     ggtitle(paste0("Soil Temps - Under Sod"))+
     #theme(axis.ticks = element_blank(), axis.text.x = element_blank()) +
     facet_wrap(year(SoilDaily$TIME), scales = "free", ncol = 5)


```

## Air Temperature
```{r Plot Air Temps, echo=FALSE, message=FALSE, warning=FALSE}


airTemp <- soilVals %>% group_by("year" = year(TIME),"month" = month(TIME), "day" = day(TIME)) %>% na.omit() %>% 
  summarise("Temp_daily" = round(mean(Temp),0)) %>% unite("Date", year, month, day, sep = "-")

airTemp$Date <- as.Date(airTemp$Date)

df <- airTemp %>% filter(year(Date) == "2018")

  ggplot(airTemp, aes(x = Date)) +
     geom_line(aes(y = Temp_daily, color = "red")) +

     theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))  +
     xlab("Month")+
     ylab("Temperature F")+
     #scale_x_discrete(limits = month.abb) +
     ggtitle(paste0("Air Temperature"))+
     #theme(axis.ticks = element_blank(), axis.text.x = element_blank()) +
     facet_wrap(year(airTemp$Date), scales = "free", ncol = 5)


```


# Ten Year Average Temperatures

```{r 10 yr temps}

library(scales)

tenYear <- airTemp %>% group_by("month" = month(Date), "day" = day(Date)) %>% 
                       summarise("daily_10_yr" = round(mean(Temp_daily),0)) %>% unite("Date", month, day, sep = "-") %>% 
                       mutate("yr" = paste0("1999-", Date))

tenYear$yr <- as_date(tenYear$yr)

  ggplot(tenYear, aes(x = yr)) +
     geom_line(aes(y = daily_10_yr, color = "red")) +

     theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))  +
     xlab("Month")+
     ylab("Temperature F")+
     #scale_x_date(limits = month.abb) +
     ggtitle(paste0("Burneyville Ten Year Average Air Temperature"))+
     #theme(axis.ticks = element_blank(), axis.text.x = element_blank()) +
     #facet_wrap(month(tenYear$yr), scales = "free", ncol = 5)
     scale_x_date(labels = label_date_short(format = c("%b")), breaks = breaks_width("1 month")) +
     theme(legend.position = "none") 

  
```


## Soil Moisture - Fractional Water Index

```{r Plot Soil Moisture, echo=FALSE, message=FALSE, warning=FALSE}


  ggplot(SoilDaily, aes(x = TIME)) +
     geom_line(aes(y = FWI_2, color = "2 inch Soil Moisture")) +
     scale_color_manual(name = "Soil Moisture", values = c("2 inch Soil Moisture" = "blue", 
                                                        "10 inch Soil Moisture" = "green"))+
     geom_line(aes(y = FWI_10, color = "10 inch Soil Moisture")) +
     theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))  +
     xlab("Month")+
     ylab("Fractional Water Index")+
     #scale_x_discrete(limits = month.abb) +
     ggtitle(paste0("Soil Moisture - Burneyville"))+
     #theme(axis.ticks = element_blank(), axis.text.x = element_blank()) +
     facet_wrap(year(SoilDaily$TIME), scales = "free", ncol = 5)




```




```{r Plot each year, echo=FALSE, message=FALSE, warning=FALSE}

#annums <- c(2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019)
annums <- c(2012:2021)


for (i in annums) {

df <- SoilDaily %>% filter(year(TIME) == i)

fred <- 
    ggplot(df, aes(x = TIME)) +
     geom_line(aes(y = Soil_Temp_Veg_2inch_daily, color = "2 inch Soil Temp")) +
     scale_color_manual(name = "Soil Temps", values = c("2 inch Soil Temp" = "blue", 
                                                        "4 inch Soil Temp" = "green"))+
     geom_line(aes(y = Soil_Temp_Veg_4inch_daily, color = "4 inch Soil Temp")) +
     theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))  +
     xlab(i)+
     ylab("Temperature F")+
       ggtitle(paste0("Soil Temps - Bare soil vs Under Vegetation - ", i))
       
print(fred)

}

```