---
title: "Burneyville Mesonet Soil Temperatures"
output:
  pdf_document: default
  html_document:
    df_print: paged
---


```{r header, echo=TRUE}
## CodeMonkey:  Mike Proctor
## ============================================================
## 
## Generates soil temperature graphs from data downloaded by Mesonet_DLoads.RMD and processed by Mesonet_Processing.R
## 
## 
```

```{r Setup, message=FALSE, warning=FALSE, include=FALSE}
library(readr)       ##  "Import dataset" uses this
library(tidyverse)   ##  mutate, transform etc.
library(lubridate)   ##  requried for ts to work
library(magrittr)    ##  %>% - pipe
library(rprojroot)   ##  find_rstudio_root_file()
library("tidylog", warn.conflicts = FALSE)
library(tictoc)

# 2019-12-05 09:47:49 ------------------------------mdp
# 2019-12-05 12:56:55 ------------------------------mdp
# 2021-01-06 09:23:53 ------------------------------mdp


## Local stuff  =================
base_path   <- find_rstudio_root_file()                        ## Finds path for project
source_path <- file.path(base_path, "source_data//")           ## these 4 should
dat_path    <- file.path(base_path, "dat_output//")            ## be existing
plot_path   <- file.path(base_path, "plots//")                 ## folders in
csv_path    <- file.path(base_path, "csv_output//")            ## project
```


```{r Load and process files, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
#soilTemps <- read_csv(paste0(source_path, "Mesonet_2007_1_1_2019_12_2.dat"))

soilTemps <- read_csv("dat_output/Mesonet_2020_1_1_2021_12_31.dat")

#names(soilTemps)[5] <- "SoilVeg_10cm"

Soils_10cm <- soilTemps %>% filter(!is.na(Soil_Veg_10cm))  ##  Soil temps are at 15min intervals so drop NAs


```




```{r Plot Soil Temps, echo=FALSE, message=FALSE, warning=FALSE}

Ten_Cm <-
  ggplot(Soils_10cm, aes(x = TIME)) +
     geom_line(aes(y = Soil_Bare_10cm, color = "Bare Soil @ 10cm")) +
     scale_color_manual(name = "Soil Temps", values = c("Bare Soil @ 10cm" = "blue", 
                                                        "Vegetated @ 10cm" = "green"))+
     geom_line(aes(y = Soil_Veg_10cm, color = "Vegetated @ 10cm")) +
     xlab("Year")+
     ylab("Temperature C")+
     ggtitle(paste0("Soil Temps - Bare soil vs Under Vegetation"))+
     theme(axis.ticks = element_blank(), axis.text.x = element_blank()) +
     facet_wrap(year(Soils_10cm$TIME), scales = "free")

print(Ten_Cm) 
```

```{r Plot each year, echo=FALSE, message=FALSE, warning=FALSE}

#annums <- c(2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019)
annums <- c(2020, 2021)

tic() 
for (i in annums) {

w <- Soils_10cm %>% filter(year(TIME) == i)

  Ten_Cm <- 
    ggplot(w, aes(x = TIME)) +
       geom_line(aes(y = Soil_Bare_10cm, color = "Bare Soil @ 10cm")) +
       scale_color_manual(name = "Soil Temps", values = c("Bare Soil @ 10cm" = "blue", 
                                                          "Vegetated @ 10cm" = "green"))+
       geom_line(aes(y = Soil_Veg_10cm, color = "Vegetated @ 10cm")) +
       xlab(i)+
       ylab("Temperature F")+
       ggtitle(paste0("Soil Temps - Bare soil vs Under Vegetation - ", i))
       

  print(Ten_Cm)

}
toc()
```